[package]
name = "format"
# Remember to update version for clap (main.rs)
version = "0.1.0"
authors = ["Martin Disch <martindisch@gmail.com>"]
edition = "2018"

[dependencies]
coap-lite = "0.2.0"
hex = "0.3.2"
clap = "2.33.0"
